name: Build and Release

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Bun
        uses: oven-sh/setup-bun@v1
        with:
          bun-version: latest

      - name: Install dependencies
        run: bun install

      - name: Build application
        run: bun run build

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: galaxycontrol-linux
          path: release/
          retention-days: 30

  release:
    needs: build
    runs-on: ubuntu-latest
    if: github.ref == 'refs/heads/main' && github.event_name == 'push'
    permissions:
      contents: write

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Download all artifacts
        uses: actions/download-artifact@v4
        with:
          path: artifacts/

      - name: Display structure of downloaded files
        run: ls -la artifacts/

      - name: Generate release tag
        id: tag
        run: |
          echo "tag=v$(date +'%Y%m%d')-${{ github.run_number }}" >> $GITHUB_OUTPUT

      - name: Create Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ steps.tag.outputs.tag }}
          name: GalaxyControl ${{ steps.tag.outputs.tag }}
          body: |
            🚀 **GalaxyControl - Automated Release**

            **Commit:** ${{ github.sha }}
            **Date:** ${{ github.event.head_commit.timestamp }}

            ## 📦 Download

            **Linux AppImage**: `GalaxyControl-Linux-*.AppImage`

            ## 🔧 Installation

            ### Linux
            1. Download the `.AppImage` file
            2. Make it executable: `chmod +x GalaxyControl-Linux-*.AppImage`
            3. Run the application: `./GalaxyControl-Linux-*.AppImage`

            ## 🎯 Features

            GalaxyControl is a GUI application to manage specific settings of Samsung Galaxy Book's driver for Linux.

            ---
            *This release was automatically generated from the latest main branch.*
          files: |
            artifacts/galaxycontrol-linux/*/GalaxyControl-Linux*.AppImage
          draft: false
          prerelease: false
          generate_release_notes: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
